services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financebot
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
